all:
	cd ./shared; make; cd ..; \
	cd ./rpc_subd; make; cd ..; \
	cd ./submarine; make; cd .. 

clean: 
	cd ./shared; make clean; cd ..; \
	cd ./rpc_subd; make clean; cd ..; \
	cd ./submarine; make clean; cd ..; \
	rm -f *~ 
