/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "../shared/sub.h"
#include "../shared/shared.h"

////function prototypes////
int movesub_prog_1(char *host, int _turn, int _x, int _y);
void print_map(int x, int y);
///////////////////////////

////main////
int main (int argc, char **argv) {
	// command line parsing	
	char *host;
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	//////GAME IMPLEMENATION///////
	int playAgain = 1;

	while (playAgain) {

		// initialization
		int x, y;
		int done = 0;
		int turn = -1;
		int c, dummy, alert;

		// coordinates for the bomb (bomb does not move during the game) 
		int xBomb, yBomb;

		srand(37);
		x = rand()%MAX_GRID;
		y = rand()%MAX_GRID;

		

		print_map(x, y);
		printf("Destroyer Start Position: X = %d   Y = %d\n", x, y);
		printf("\n\n\n\n\n\n\n");

		while (!done){
			printf("Enter Command> ");
			c = getchar(); 
			dummy = getchar();	//for the newline
			switch (c){
				case 'x': 
					printf("Exit on command. Bye!\n"); exit(0);
				case '7': 
					x = (x + MAX_GRID - 1) % MAX_GRID;
				case '8': 
					y = (y + MAX_GRID - 1) % MAX_GRID; 
					turn++; 
					break;
				case '9': 
					y = (y + MAX_GRID - 1) % MAX_GRID;
				case '6': 
					x = (x + MAX_GRID + 1) % MAX_GRID; 
					turn++; 
					break;
				case '3': 
					x = (x + MAX_GRID + 1) % MAX_GRID;
				case '2': 
					y = (y + MAX_GRID + 1) % MAX_GRID; 
					turn++; 
					break;
				case '1': 
					y = (y + MAX_GRID + 1) % MAX_GRID;
				case '4': 
					x = (x + MAX_GRID - 1) % MAX_GRID; 
					turn++; 
					break;
				case '5': 
					turn++; 
					break;
				default : 
					printf("Illegal movement: %c\n", c); 
					break;
			}
			#if DEBUG
			printf("Destroyer Position: X = %d   Y = %d\n", x, y);
			#endif

			print_map(x, y);
			printf("Turn:%3d Dir:%c X = %d   Y = %d\n", turn, c, x, y);

			alert = movesub_prog_1 (host, turn, x, y);
			switch(alert){
				case -1:
					printf("Hit by a bomb :( You lose.\n");
					done = 1;
					break;
				case 0: 
					printf("Hit! Congratulation! End game.\n"); 
					done = 1; 
					break;
				case 1: 
					printf("Red Alert!!!\n"); 
					break;
				case 2: 
					printf("Yellow Alert!!\n"); 
					break;
				case 3: 
					printf("Green Alert!\n"); 
					break;
				case 4:
					printf("Submarine hits the bomb. Congratulations! End game.\n");
					done = 1;
					break;
			}
			printf("\n\n\n");
	 	}

		done = 0;
		printf("\nPlay again (y/n)? >");
		int again = getchar();
		dummy = getchar();	//capture the newline
		//if the character is not 'y', then assume do not play again
		if (again != 'y') playAgain = 0;	
	
	}

	exit (0);
}
////////////



////movesub_prog_1////
int movesub_prog_1(char *host, int _turn, int _x, int _y) {
	CLIENT *clnt;
	int  *result_1;
	moveStruct moveArg;
	
	//fill in argument structure
	moveArg.turn = _turn;
	moveArg.x1 = _x;
	moveArg.y1 = _y;

	#ifndef	DEBUG
		clnt = clnt_create (host, MOVESUB_PROG, MOVESUB_VERSION, "udp");
		if (clnt == NULL) {
			clnt_pcreateerror (host);
			exit (1);
		}
	#endif

	result_1 = movesub_proc_1(&moveArg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	#ifndef	DEBUG
		clnt_destroy (clnt);
	#endif

	return *result_1;

}
//////////////////////

////print_map////
// implemented on the client because it has to be displayed on the client's screen. 
void print_map(int x, int y) {
	int i, j;
	printf("\nFind the Hidden Submarine: Written by Prof. Joseph Ng\n");
	printf("Ocean Map:\n ");
	for (i = 0; i < MAX_GRID; i++) 
		printf(" %d", i); 
	printf("\n");
	for (i = 0; i < MAX_GRID; i++) {
		printf("%d", i);
		for (j = 0; j < MAX_GRID; j++) {
         		if ((i == y) && (j == x)) printf(" D"); 
			else printf(" .");
		}
		printf("\n");
	}

	printf("\n\n\nMessage:\n");
}
/////////////////
